void testSingleNumber();
void testTwoNumbers();
void testUnknownAmountOfNumbers();
void testNewlinesAsDelimiters();
void testCustomSingleCharDelimiter();
void testCustomMultiCharDelimiter();
void testMultipleCustomDelimiters();
void testNegativeNumbersThrow();
void testNumbersOver1000Ignored();
